refactor cleanup workflow and add migration job

diff --git a/.github/workflows/cleanup-database.yml b/.github/workflows/cleanup-database.yml
--- a/.github/workflows/cleanup-database.yml
+++ b/.github/workflows/cleanup-database.yml
@@ -17,7 +17,7 @@ on:
         default: alkemio
 
 jobs:
-  cleanup-postgres:
+  cleanup-db:
     runs-on: ubuntu-latest
     steps:
       - name: Install Kubectl
@@ -74,3 +74,47 @@ jobs:
           echo "Dropping and recreating database $POSTGRES_DB..."
           PGPASSWORD="$POSTGRES_PASSWORD" psql -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" -d postgres -c "DROP DATABASE IF EXISTS \"$POSTGRES_DB\";"
           PGPASSWORD="$POSTGRES_PASSWORD" psql -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE \"$POSTGRES_DB\";"
+
+
+  run-migration-and-boostrap:
+    needs: cleanup-db
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Kubectl
+        uses: azure/setup-kubectl@v4.0.0
+        with:
+          version: "v1.29.6" # Ensure this matches the version used in your cluster
+
+      - name: Set up Kubeconfig for Hetzner k3s
+        run: |
+          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
+          echo "${{ secrets.KUBECONFIG_SECRET_HETZNER_TEST }}" > $HOME/.kube/config
+          chmod 600 $HOME/.kube/config
+      # apply the latest schema
+      - name: Run migration job
+        run: |
+          # Define a unique job name based on the GitHub run ID
+          MIGRATION_JOB_NAME="server-migration-job-${{ github.run_id }}"
+
+          # Create the job from the cronjob
+          kubectl create job --from=cronjob/server-migration $MIGRATION_JOB_NAME
+
+          # Wait for the migration job to complete
+          kubectl wait --for=condition=complete job/$MIGRATION_JOB_NAME --timeout=600s
+
+          # Check job status and fail the step if the job didn't succeed
+          MIGRATION_JOB_STATUS=$(kubectl get job $MIGRATION_JOB_NAME -o jsonpath='{.status.succeeded}')
+          if [ "$MIGRATION_JOB_STATUS" != "1" ]; then
+            echo "Migration job failed!"
+            exit 1
+          fi
+
+          echo "Migration job completed successfully."
+        # restart the server so it picks up the new database state and bootstraps
+      - name: Restart deployment
+        run: |
+          # Restart the deployment
+          kubectl rollout restart deployment/alkemio-server-deployment
+
+          # Wait for the deployment to complete successfully
+          kubectl rollout status deployment/alkemio-server-deployment --timeout=600s
